name: Deploy to Digital Ocean

on:
  push:
    paths:
      - 'personal_resume_website/**'
      - '.github/workflows/deploy-digital-ocean.yml'
  pull_request:
    paths:
      - 'personal_resume_website/**'
      - '.github/workflows/deploy-digital-ocean.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug - Print environment variables
        run: env | sort

      - name: Check if DO_TOKEN is set
        run: |
          if [ -z "${DO_TOKEN}" ]; then 
            echo "DO_TOKEN is not set"; 
            exit 1; 
          else 
            echo "DO_TOKEN is set"; 
          fi
        env:
          DO_TOKEN: ${{ secrets.DO_TOKEN }}

      - name: Cache Terraform Providers
        uses: actions/cache@v3
        with:
          path: ~/.terraform.d/plugins
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
        env:
          DO_TOKEN: ${{ secrets.DO_TOKEN }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve
        env:
          DO_TOKEN: ${{ secrets.DO_TOKEN }}