name: Deploy and Configure

on:
  push:
    paths:
      - 'personal-website/**'
      - '.github/workflows/deploy-digital-ocean.yml'
  pull_request:
    paths:
      - 'personal-website/**'
      - '.github/workflows/deploy-digital-ocean.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="DO_TOKEN=${{ secrets.DO_TOKEN }}" -var="SSH_PUBLIC_KEY=${{ secrets.SSH_PUBLIC_KEY }}" -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        run: terraform apply -var="DO_TOKEN=${{ secrets.DO_TOKEN }}" -var="SSH_PUBLIC_KEY=${{ secrets.SSH_PUBLIC_KEY }}" -auto-approve

  ansible:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Droplet IP
        uses: actions/download-artifact@v3
        with:
          name: droplet_ip
          path: .

      - name: Display Droplet IP
        run: |
          DROPLET_IP=$(cat droplet_ip.txt)
          echo "Droplet IP: $DROPLET_IP"

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: false
        run: |
          DROPLET_IP=$(cat droplet_ip.txt)
          ansible-playbook -i "${DROPLET_IP}," -u root --private-key ~/.ssh/id_rsa -vvvv ansible/site.yml